services:
  nginx:
    build: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - frontend
      - backend
    networks:
      - eatai-net

  frontend:
    build: ./frontend
    expose:
      - "${FRONTEND_PORT}"
    networks:
      - eatai-net
    deploy:
      replicas: 3
    restart: unless-stopped

  backend:
    build: ./backend
    expose:
      - "${BACKEND_PORT}"
    env_file:
      - .env
    networks:
      - eatai-net
    restart: unless-stopped

  database:
    build: ./postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - eatai-net

volumes:
  db_data:

networks:
  eatai-net:
